/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
/**
 * 
 * @export
 * @interface LocationCoordinates
 */
export interface LocationCoordinates {
    /**
     * 
     * @type {number}
     * @memberof LocationCoordinates
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationCoordinates
     */
    latitude?: number;
}

/**
 * Check if a given object implements the LocationCoordinates interface.
 */
export function instanceOfLocationCoordinates(value: object): value is LocationCoordinates {
    return true;
}

export function LocationCoordinatesFromJSON(json: any): LocationCoordinates {
    return LocationCoordinatesFromJSONTyped(json, false);
}

export function LocationCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationCoordinates {
    if (json == null) {
        return json;
    }
    return {
        
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
    };
}

export function LocationCoordinatesToJSON(json: any): LocationCoordinates {
    return LocationCoordinatesToJSONTyped(json, false);
}

export function LocationCoordinatesToJSONTyped(value?: LocationCoordinates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'longitude': value['longitude'],
        'latitude': value['latitude'],
    };
}

