/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OfficeType = {
    Office1: 'Office 1',
    Office2: 'Office 2',
    Office3: 'Office 3'
} as const;
export type OfficeType = typeof OfficeType[keyof typeof OfficeType];


export function instanceOfOfficeType(value: any): boolean {
    for (const key in OfficeType) {
        if (Object.prototype.hasOwnProperty.call(OfficeType, key)) {
            if (OfficeType[key as keyof typeof OfficeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OfficeTypeFromJSON(json: any): OfficeType {
    return OfficeTypeFromJSONTyped(json, false);
}

export function OfficeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfficeType {
    return json as OfficeType;
}

export function OfficeTypeToJSON(value?: OfficeType | null): any {
    return value as any;
}

export function OfficeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OfficeType {
    return value as OfficeType;
}

