/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OfficerRole = {
    Role1: 'Role 1',
    Role2: 'Role 2',
    Role3: 'Role 3'
} as const;
export type OfficerRole = typeof OfficerRole[keyof typeof OfficerRole];


export function instanceOfOfficerRole(value: any): boolean {
    for (const key in OfficerRole) {
        if (Object.prototype.hasOwnProperty.call(OfficerRole, key)) {
            if (OfficerRole[key as keyof typeof OfficerRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OfficerRoleFromJSON(json: any): OfficerRole {
    return OfficerRoleFromJSONTyped(json, false);
}

export function OfficerRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfficerRole {
    return json as OfficerRole;
}

export function OfficerRoleToJSON(value?: OfficerRole | null): any {
    return value as any;
}

export function OfficerRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): OfficerRole {
    return value as OfficerRole;
}

