/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ReportDocument } from './ReportDocument';
import {
    ReportDocumentFromJSON,
    ReportDocumentFromJSONTyped,
    ReportDocumentToJSON,
    ReportDocumentToJSONTyped,
} from './ReportDocument';
import type { OfficeType } from './OfficeType';
import {
    OfficeTypeFromJSON,
    OfficeTypeFromJSONTyped,
    OfficeTypeToJSON,
    OfficeTypeToJSONTyped,
} from './OfficeType';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    title?: string;
    /**
     * 
     * @type {Location}
     * @memberof Report
     */
    location?: Location;
    /**
     * 
     * @type {User}
     * @memberof Report
     */
    author?: User;
    /**
     * 
     * @type {boolean}
     * @memberof Report
     */
    anonymity?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    date?: string;
    /**
     * 
     * @type {OfficeType}
     * @memberof Report
     */
    category?: OfficeType;
    /**
     * 
     * @type {ReportDocument}
     * @memberof Report
     */
    document?: ReportDocument;
    /**
     * Current state of the report
     * @type {string}
     * @memberof Report
     */
    state?: string;
    /**
     * Id of the officer assigned to the report (if any)
     * @type {number}
     * @memberof Report
     */
    assignedOfficerId?: number;
    /**
     * Id of the maintainer assigned to the report (if any)
     * @type {number}
     * @memberof Report
     */
    assignedMaintainerId?: number;
    /**
     * Optional reason (for declines etc.)
     * @type {string}
     * @memberof Report
     */
    reason?: string;
    /**
     * Users that follow this report
     * @type {Array<User>}
     * @memberof Report
     */
    followerUsers?: Array<User>;
}
/*

  @Column({ type: "text", default: ReportState.PENDING })
  state!: ReportState;

  @Column({ type: "text", nullable: true })
  reason!: string | null;

  @Column({ type: "integer", nullable: true })
  assignedOfficerId!: number | null;

    */
/**
 * Check if a given object implements the Report interface.
 */
export function instanceOfReport(value: object): value is Report {
    return true;
}

export function ReportFromJSON(json: any): Report {
    return ReportFromJSONTyped(json, false);
}

export function ReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
        'author': json['Author'] == null ? undefined : UserFromJSON(json['Author']),
        'anonymity': json['Anonymity'] == null ? undefined : json['Anonymity'],
        'date': json['Date'] == null ? undefined : json['Date'],
        'category': json['Category'] == null ? undefined : OfficeTypeFromJSON(json['Category']),
        'document': json['Document'] == null ? undefined : ReportDocumentFromJSON(json['Document']),
        'state': json['state'] == null ? (json['State'] == null ? undefined : json['State']) : json['state'],
        'assignedOfficerId': json['assignedOfficerId'] == null ? (json['AssignedOfficerId'] == null ? undefined : json['AssignedOfficerId']) : json['assignedOfficerId'],
        'assignedMaintainerId': json['assignedMaintainerId'] == null ? (json['AssignedMaintainerId'] == null ? undefined : json['AssignedMaintainerId']) : json['assignedMaintainerId'],
        'reason': json['reason'] == null ? (json['Reason'] == null ? undefined : json['Reason']) : json['reason'],
        'followerUsers': json['followerUsers'] == null ? undefined : (json['followerUsers'] as Array<any>).map(UserFromJSON),
    };
}

export function ReportToJSON(json: any): Report {
    return ReportToJSONTyped(json, false);
}

export function ReportToJSONTyped(value?: Report | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'location': LocationToJSON(value['location']),
        'Author': UserToJSON(value['author']),
        'Anonymity': value['anonymity'],
        'Date': value['date'],
        'Category': OfficeTypeToJSON(value['category']),
        'Document': ReportDocumentToJSON(value['document']),
        'state': value['state'],
        'assignedOfficerId': value['assignedOfficerId'],
        'assignedMaintainerId': value['assignedMaintainerId'],
        'reason': value['reason'],
        'followerUsers': value['followerUsers'] == null ? undefined : (value['followerUsers'] as Array<User>).map(UserToJSON),
    };
}

