/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
import type { Report } from './Report';
import {
    ReportFromJSON,
    ReportFromJSONTyped,
    ReportToJSON,
    ReportToJSONTyped,
} from './Report';
import type { State } from './State';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State';
import type { Officer } from './Officer';
import {
    OfficerFromJSON,
    OfficerFromJSONTyped,
    OfficerToJSON,
    OfficerToJSONTyped,
} from './Officer';

/**
 * 
 * @export
 * @interface ReportState
 */
export interface ReportState {
    /**
     * 
     * @type {Report}
     * @memberof ReportState
     */
    report?: Report;
    /**
     * 
     * @type {State}
     * @memberof ReportState
     */
    approved?: State;
    /**
     * 
     * @type {string}
     * @memberof ReportState
     */
    reason?: string;
    /**
     * 
     * @type {Officer}
     * @memberof ReportState
     */
    officer?: Officer;
}



/**
 * Check if a given object implements the ReportState interface.
 */
export function instanceOfReportState(value: object): value is ReportState {
    return true;
}

export function ReportStateFromJSON(json: any): ReportState {
    return ReportStateFromJSONTyped(json, false);
}

export function ReportStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportState {
    if (json == null) {
        return json;
    }
    return {
        
        'report': json['Report'] == null ? undefined : ReportFromJSON(json['Report']),
        'approved': json['Approved'] == null ? undefined : StateFromJSON(json['Approved']),
        'reason': json['Reason'] == null ? undefined : json['Reason'],
        'officer': json['Officer'] == null ? undefined : OfficerFromJSON(json['Officer']),
    };
}

export function ReportStateToJSON(json: any): ReportState {
    return ReportStateToJSONTyped(json, false);
}

export function ReportStateToJSONTyped(value?: ReportState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Report': ReportToJSON(value['report']),
        'Approved': StateToJSON(value['approved']),
        'Reason': value['reason'],
        'Officer': OfficerToJSON(value['officer']),
    };
}

