/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
/**
 * 
 * @export
 * @interface ReportDocument
 */
export interface ReportDocument {
    /**
     * 
     * @type {string}
     * @memberof ReportDocument
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportDocument
     */
    photos?: Array<string>;
}

/**
 * Check if a given object implements the ReportDocument interface.
 */
export function instanceOfReportDocument(value: object): value is ReportDocument {
    return true;
}

export function ReportDocumentFromJSON(json: any): ReportDocument {
    return ReportDocumentFromJSONTyped(json, false);
}

export function ReportDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'] == null ? undefined : json['Description'],
        'photos': json['Photos'] == null ? undefined : json['Photos'],
    };
}

export function ReportDocumentToJSON(json: any): ReportDocument {
    return ReportDocumentToJSONTyped(json, false);
}

export function ReportDocumentToJSONTyped(value?: ReportDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Description': value['description'],
        'Photos': value['photos'],
    };
}

