/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const State = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Declined: 'DECLINED'
} as const;
export type State = typeof State[keyof typeof State];


export function instanceOfState(value: any): boolean {
    for (const key in State) {
        if (Object.prototype.hasOwnProperty.call(State, key)) {
            if (State[key as keyof typeof State] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    return json as State;
}

export function StateToJSON(value?: State | null): any {
    return value as any;
}

export function StateToJSONTyped(value: any, ignoreDiscriminator: boolean): State {
    return value as State;
}

