/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
import type { Report } from './Report';
import { ReportFromJSON, ReportToJSON } from './Report';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    telegramUsername?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    emailNotifications?: boolean;
    /**
     * Reports followed by the user
     * @type {Array<Report>}
     * @memberof User
     */
    followedReports?: Array<Report>;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'password': json['password'] == null ? undefined : json['password'],
        'email': json['email'] == null ? undefined : json['email'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'telegramUsername': json['telegramUsername'] == null ? undefined : json['telegramUsername'],
        'emailNotifications': json['emailNotifications'] == null ? undefined : json['emailNotifications'],
        'followedReports': json['followedReports'] == null ? undefined : (json['followedReports'] as Array<any>).map(ReportFromJSON),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'password': value['password'],
        'email': value['email'],
        'avatar': value['avatar'],
        'telegramUsername': value['telegramUsername'],
        'emailNotifications': value['emailNotifications'],
        'followedReports': value['followedReports'] == null ? undefined : (value['followedReports'] as Array<Report>).map(ReportToJSON),
    };
}

